apiVersion: v1
kind: Service
metadata:
  name: my-python-service
spec:
  selector:
    app: my-python-app
  ports:
  - protocol: TCP
    port: 32777  
    targetPort: 32777
    nodePort: 32777
  type: NodePort